var RapidAPI = new require('rapidapi-connect');
var rapid = new RapidAPI('Demo', '############'); //Your RapidAPI Account number

//Retreiving GIF text and target phone number from command line
var gifText = process.argv[2];
var phoneNumber = process.argv[3];

rapid.call('Giphy', 'translateTextToGif', { 
        'rating': 'pg',
        'apiKey': '###########', //This is GIPHY's public beta key
        'text': gifText, //This value needs to be input by user
        'lang': 'en'
    }).on('success', (payload)=>{
        var gif = payload.data.images.fixed_height.url;
        rapid.call('Twilio', 'sendMms', { 
            'from': '+###########', //This is the phone number you register on Twilio
            'to': phoneNumber,//This value needs to be input by user
            'applicationSid': '',
            'statusCallback': '',
            'accountSid': '####################',//This is your Twilio accountSid number (from registering a Twilio account)
            'accountToken': '###################',//This is your Twilio accountToken (from registering a Twilio account)
            'messagingServiceSid': '################',//This is your Twilio messagingSid number (from registering Twilio messaging functionality)
            'mediaUrl': gif, //This link will be generated by Giphy API
            'maxPrice': '',
            'provideFeedback': ''
        }).on('success', (payload)=>{

             console.log("Check your phone!");
        }).on('error', (payload)=>{
             console.log("Error sending MMS");
        });

    }).on('error', (payload)=>{
        res.send("Error finding GIF");
    });